# Generated by Django 3.2.9 on 2021-12-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
