# Generated by Django 3.2.9 on 2021-12-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=20000)),
                ('starting_bid', models.PositiveIntegerField()),
                ('image_file', models.ImageField(upload_to='images')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_bid', models.PositiveIntegerField()),
                ('current_bid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comments_AL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_list', to='auctions.auction_listings')),
            ],
        ),
    ]
