# Generated by Django 3.2.9 on 2021-12-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
