# Generated by Django 3.2.9 on 2021-12-09 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_delete_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_al',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments_al',
            name='AL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_list', to='auctions.auction_listings'),
        ),
        migrations.AlterField(
            model_name='comments_al',
            name='comment',
            field=models.TextField(max_length=2000),
        ),
        migrations.RemoveField(
            model_name='comments_al',
            name='user',
        ),
        migrations.AddField(
            model_name='comments_al',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
