# Generated by Django 3.2.9 on 2021-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_listings_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User2',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(choices=[('LAP', 'Laptop'), ('CON', 'Console'), ('GAD', 'Gadget'), ('GAM', 'Game'), ('TEL', 'TV')], max_length=45),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
