# Generated by Django 3.2.9 on 2021-12-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211204_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='starting_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_bid', to='auctions.auction_listings', unique=True),
        ),
        migrations.AlterField(
            model_name='comments_al',
            name='AL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_list', to='auctions.auction_listings', unique=True),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listings', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
