# Generated by Django 3.2.9 on 2021-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211205_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction_listings',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='user',
            name='wishlisted',
            field=models.ManyToManyField(to='auctions.Auction_Listings'),
        ),
    ]
