# Generated by Django 3.2.9 on 2021-12-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='starting_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
